### PR TITLE
Fix permission of dropbear_acl target file for installation

### LINKED ISSUE #78: dropbear_acl target file cannot be owned by users other than root
For an sudoer setup, I'd want to keep things out of the `/root` folder if possible.

Right now, dracut-crypt-ssh provides a `dropbear_acl` setting for reusing authorized SSH keys for dropbear SSH login. This is great for system that allows root to use SSH. But for some of my setup, I usually do not allow that. So my `/root/.ssh/authorized` file in those system do not exists.

I'd prefer to setup my dropbear to use `/home/foobar/.ssh/authorized_keys` instead. In which case, the `authorized_keys` file naturally belongs to the user `foobar`.

In the [latest current version](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/commit/de3c2b9ffceae77f04b3aa2c05cf0f377f0c39a8), the `authorized_keys` file is just copied to the dropbear environment. And for security reason, the file is expected to be owned by root to work. So if I setup `dropbear_acl="/home/foobar/.ssh/authorized_keys"`, although the file is correctly installed to dropbear environment, the login would fail because of incorrect ownereship.

It would be better if the file's permission is fixed after installing to dropbear environment.

### PR DESCRIPTION
**Pull request by yookoala**
* Fix the ownership and permission of the dropbear_acl target file for dracut to use as /root/.ssh/authorized_keys.
* Fixes #78.

### CODE REVIEW

**Comment by ahesford** [comment]
This should just fix the permissions on the target file directly, rather than making an intermediate copy that isn't cleaned up.

**Comment by yookoala** [comment]
> This should just fix the permissions on the target file directly, rather than making an intermediate copy that isn't cleaned up.

The intermediate copy is created in the `$tmpDir` so it is cleaned up OK.

With sudoer setup, usually the `authorized_keys` file with the sudoer account has all the keys that are supposed to be accessible to the account with ssh. I set it to the `dropbear_acl` target file because I do not want to keep 2 version of the file and simply want to reuse it.

If I set the file to be owned by root, then ssh won't be login to the regular user. I think forcing `dropbear_acl` to have the same permission as the supposed `/root/.ssh/authorized_keys` is not the proper solution here.

**Comment by ahesford** [comment]
I'm not telling you to change the permissions of the source file, but to adjust the permissions of the destination *after it's copied*.

**Comment by yookoala** [comment]
> I'm not telling you to change the permissions of the source file, but to adjust the permissions of the destination _after it's copied_.

I'm sorry but I'm not familiar with dracut enough to do this. [dracut.modules](https://www.man7.org/linux/man-pages/man7/dracut.modules.7.html) documentation does not provide a command / function to change a file's permission or ownership after `inst`.

Please advice how it should be done. Thanks a lot.

**Comment by zdykstra** [comment]
> > I'm not telling you to change the permissions of the source file, but to adjust the permissions of the destination _after it's copied_.
> 
> I'm sorry but I'm not familiar with dracut enough to do this. [dracut.modules](https://www.man7.org/linux/man-pages/man7/dracut.modules.7.html) documentation does not provide a command / function to change a file's permission or ownership after `inst`.
> 
> Please advice how it should be done. Thanks a lot.

Files installed in the initramfs are available at `${initdir}/their/installed/path`, so in this case it'd be `${initdir}/root/.ssh/authorized_keys` .

**Comment by yookoala** [comment]
@zdykstra: Thanks! Updated.

**Comment by yookoala** [comment]
@ahesford: I've already updated according to your previous comment. Is there anything still needed to change in this PR before merge?

File: modules/60crypt-ssh/module-setup.sh [hunk 1]
```diff
@@ -106,7 +106,10 @@ install() {
   inst_hook pre-udev 99 "$moddir/dropbear-start.sh"
   inst_hook pre-pivot 05 "$moddir/dropbear-stop.sh"
 
+  #install the authorized_keys file and fix the ownership/permission
   inst "${dropbear_acl}" /root/.ssh/authorized_keys
+  chmod 400 ${initdir}/root/.ssh/authorized_keys
+  chown root:root ${initdir}/root/.ssh/authorized_keys
```
Comment (ahesford) [inline modules/60crypt-ssh/module-setup.sh]: It's better to use `0:0` instead of `root:root` here, in case some weird environment doesn't map `root` to uid 0.

**Review by ahesford — CHANGES_REQUESTED** [review]

**Comment by yookoala** [comment]
@ahesford: Done. Please check.
